import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { SideBarProviderState } from "@/store/contexts/sideBarContext";
import {
  SidebarProvider as ShadcnSidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SideBarProviderState>
          <ShadcnSidebarProvider>
            <div className="flex h-screen w-full">
              <AppSidebar />
              <div className="w-full">
                <SidebarTrigger className="absolute" />
                <main className="flex-1 overflow-auto">{children}</main>
              </div>
            </div>
          </ShadcnSidebarProvider>
        </SideBarProviderState>
      </body>
    </html>
  );
}
